import os

from dotenv import load_dotenv

from google import genai


# ==========================
# Load Environment Variables
# ==========================

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")


# ==========================
# Configure Gemini Client
# ==========================

client = genai.Client(
    api_key=API_KEY
)


# ==========================
# AI Security Assistant
# ==========================

def generate_ai_response(

    scan_type,

    status,

    risk_score,

    ml_prediction,

    ml_confidence,

    reasons

):

    prompt = f"""
You are SentinelX AI Security Assistant.

You are an expert Cybersecurity Analyst.

Your job is to explain scan results in simple English so that even a non-technical user can understand them.

==================================================

Scan Type:
{scan_type}

Status:
{status}

Risk Score:
{risk_score}

Machine Learning Prediction:
{ml_prediction}

Confidence:
{ml_confidence}%

Detection Reasons:
{chr(10).join(reasons)}

==================================================

Generate the response using these headings.

## Overall Summary

Explain what this scan means.

## Why was this classified?

Explain every detection reason in simple language.

## Risk Assessment

Explain what could happen if the user ignores this warning.

## Should I Use It?

If Safe:
Explain why it appears safe but mention that no automated system guarantees 100% safety.

If Suspicious:
Tell the user to proceed carefully.

If Dangerous:
Strongly recommend avoiding it.

## Recommendations

Give 5 practical cybersecurity recommendations.

## Cybersecurity Tips

Provide useful cyber safety tips related to this scan type.

Rules:

- Never exaggerate.
- Never invent facts.
- Base your explanation only on the supplied scan result.
- Use professional but simple English.
- Use markdown headings and bullet points.
"""

    try:

        response = client.models.generate_content(

            model="gemini-2.5-flash",

            contents=prompt

        )

        return response.text

    except Exception as e:

        return f"""
# AI Security Assistant

AI Security Assistant is currently unavailable.

**Error:**
{str(e)}

The phishing detection result shown above is still valid because it was generated by the Rule-Based Engine and Machine Learning model.
"""