# Generated by Django 5.2.3 on 2026-06-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_scanhistory_ml_confidence_scanhistory_ml_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='scan_type',
            field=models.CharField(choices=[('URL', 'URL'), ('EMAIL', 'EMAIL')], default='URL', max_length=20),
        ),
    ]
