# Generated by Django 5.2.3 on 2026-06-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_scanhistory_email_content_scanhistory_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='file_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='image_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_type',
            field=models.CharField(choices=[('URL', 'URL'), ('EMAIL', 'EMAIL'), ('IMAGE', 'IMAGE'), ('FILE', 'FILE')], default='URL', max_length=20),
        ),
    ]
